# Questão 02 - ESCREVA UM PROGRAMA QUE LEIA UM NÙMERO E VERIFIQUESE E OU NÃO UM NÙMERO PRIMO. PARA FAZER ESTA
# VERIFICAÇÃO, CALCULE O RESTO DA DIVISÃO DO NÚMERO POR 2 E DEPOIS POR TODOS OS NÚMEROS IMPARES ATÉ O NÚMERO LIDO. SE
# O RESTO DE UMA DESTAS DIVISÕES FOR IGUAL A ZERO, O NÚMERO NÃO É PRIMO. OBSERVE QUE O 0 E 1 NÃO SÃO PRIMOS E QUE 2
# É O ÚNICO NÚMERO PRIMO QUE É PAR.